# Generated by Django 4.1 on 2022-08-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
