# Generated by Django 4.1 on 2022-08-24 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cryptoapi", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cryptocoin",
            old_name="date_time",
            new_name="date",
        ),
    ]
